spring:
  application:
    name: growit

  datasource:
    url: jdbc:postgresql://localhost:5432/Growit
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  expired-second: 3600
  refresh-expired-second: 86400
  secret-key: mySuperSecureKeyThatIsMoreThan32BytesLong123
